### ISSUE TITLE
Split up cloudendure.py logic

### ISSUE THREAD

**Issue by mbeacom** [2ndWatch/cloudendure-python#30]
### User Story

As a CE contributor, I want to more easily find appropriate methods throughout the codebase.

#### Acceptance Criteria

- [ ] Breakout functionality defined in `cloudendure/cloudendure.py` into relevantly named modules.
- [ ] Remove overlap/duplicate code and DRY up the codebase.

**Comment by mbeacom** [comment]
This is going to be a bigger pain than originally anticipated because of the general structuring of the CLI with `fire`.
We'll probably want to discuss this before proceeding @twarnock2w

**Comment by twarnock2w** [comment]
Wrote some lambdas that have some of the functionality broken out.  Should be organized in order to run well with CLI and step functions.
