### ISSUE TITLE
Migrate environment management from pipenv to poetry

### ISSUE THREAD

**Issue by selpan** [2ndWatch/cloudendure-python#97]
This conversion from pipenv to poetry is at the request of the project maintainer. The conversion has been completed and will be offered as a PR for review at the maintainer's convenience.

**Comment by selpan** [comment]
Ah, missed the `Makefile` changes.  I'll update that later 👍

**Comment by selpan** [comment]
Should be good for review at this point.  The PR is testing out fine now but could still do with a sanity check for the conversion actions.

**Comment by mbeacom** [comment]
Closed in #98
